### ISSUE TITLE
Shapeless derivation ignores instances in companion object

### ISSUE THREAD

**Issue by iRevive** [neotypes/neotypes#197]
## Background

```scala
import neotypes.implicits.mappers.results._

final case class ObjectScope(value: String)

object ObjectScope {
  val const = ObjectScope("const")
  implicit val resultMapper: ResultMapper[ObjectScope] = ResultMapper.const(const)
}

ResultMapper[ObjectScope].to(Nil, None) // Left(neotypes.exceptions$PropertyNotFoundException: Property value not found)

// Expected Right(ObjectScope(const))
```

`ResultMapper[ObjectScope]` expands into 
```ResultMapper[ObjectScope](neotypes.implicits.mappers.results.ccMarshallable)```.

From the compiler perspective, everything is correct. From the user perspective, it's a painful experience.  

Instances for alias/opaque/newtype types are ignored.

## Workaround

```
import neotypes.implicits.mappers.results.{ccMarshallable => _, _}
```

## Solution

What if we follow the auto/semiauto pattern here? 

1) Move shapeless-based derivation into a separate folder `neotypes.generic`
2) Introduce `auto` and `semiauto` derivation
3) Use dedicated types for the shapeless-specific result mappers: `DerviedResultMapper` for product and `RepResultMapper` for HList.

## Pros/Cons

Pros:
- `neotypes.generic.semiauto` can work together with https://github.com/scalaz/scalaz-deriving
- primitive instances are isolated
- more control about imports
- more options for external instances: manual, magnolia-based, etc

Cons:
- Wildcard import of `neotypes.generic.auto._` still leads to the problem explained in the post. But at least instances for primitives can be imported safely `import neotypes.implicits.mappers.results._`
- the change is source/binary breaking

What's your opinion on this topic? If you are interesting, I can pick it up and contribute.

**Comment by BalmungSan** [comment]
Related to #121 

Actually, we wanted to make a similar _(but probably simpler change)_ some time ago.
In the end, we didn't make it because we want to move out from implicit encoders to explicit ones _(like in **Skunk**)_ with utilities to automatically derive simple encoders for case cases; and it wasn't affecting anyone at that time _(at least not that we know)_
However, we haven't advanced that much on that regard.

Since this is already being a pain point for someone I am more eager to fix it, even if that means changing it latter.

> If you are interesting, I can pick it up and contribute.

That would be awesome!

**Comment by iRevive** [comment]
@BalmungSan thank's for the response! 

I will make a prototype in several days.
