### ISSUE TITLE
neotypes.generic not available in 1.5.1 jar from sbt

### ISSUE THREAD

**Issue by ValRCS** [neotypes/neotypes#209]
Getting started example found at
https://neotypes.github.io/neotypes/ is not working fully(connection works, queries implicits don't)

Reason:
//  import neotypes.generic.auto._ is not working

Reason:
the whole generic is missing from sbt: com.dimafeng:neotypes_2.13:0.15.1:jar (internal and implicits are there)

//SBT
libraryDependencies += "com.dimafeng" %% "neotypes" % "0.15.1"

//checked also 0.15.0 and 0.14.0, but not found since generic is a recent addition :)

Thank you for the great library!

**Comment by BalmungSan** [comment]
Hello @ValRCS sorry for the confusion.

The **generic** module has not be released yet because it will be part of `0.16.0`, it wasn't a thing when `0.15.1` was published.

For now you can `import neotypes.implicits.mappers.all._` to get the same results.

------

The real problem here is that we publish the site and docs form master, but maybe we should publish the one from the last tag?
What do you think @dimafeng

**Comment by dimafeng** [comment]
hm, good question. I can check if it's possible to publish from a tag in my github actions POC

**Comment by nikodemin** [comment]
Hello! I had similar problem, so I added this import, but there are additional implicits requared.
Example: `c"CREATE (o: Order {$order}) RETURN ID(o)".query[Long].execute(session)`
For this query implicit value of mapper.ExecutionMapper[Long] is required. So could you suggest a workaround? Or maybe could you tell when `0.16.0` will be released?
Thank you in advance!

**Comment by BalmungSan** [comment]
Hi @nikodemin sorry for the troubles.

We should be releasing `0.16.0` soon, since we decided to stop waiting for a proper fix for neo4j/neo4j-java-driver#797 and we rather workaround it _(although on an unsafe way)_.

Until then, you should be ok if you only `import neotypes.implicits.mappers.all._` or `import neotypes.implicits.all._`

**Comment by BalmungSan** [comment]
Hi @ValRCS and @nikodemin

Sorry for taking too long, but finally `0.16.0` is released with the generic module!
