### ISSUE TITLE
Feature: Expose test harness as a separate library

### ISSUE THREAD

**Issue by tjarvstrand** [neotypes/neotypes#287]
I'm just getting into Neo4j with Scala and found out that the official Neo4j test harness doesn't even support 2.13 yet :/

I think it would be a huge boon to the community if neotypes exposed their own test harness as a library so that users don't have to roll their own.

**Comment by BalmungSan** [comment]
Hi @tjarvstrand 

> official Neo4j test harness doesn't even support 2.13

From what I can see that is a **Java** library, so it should just work with any **Scala** version, it doesn't know anything about **Scala**. Not sure if I am missing something.

> I think it would be a huge boon to the community if neotypes exposed their own test harness as a library so that users don't have to roll their own.

While I agree it would be cool to have that, for what I understand _(I may be wrong)_ the test harness is more to test custom procedures and things like that, rather than normal queries.

Right now, **neotypes** is focusses on providing a driver to interact with **neo4j** by wrapping what the official **Java** driver does. As such, I think it would be better to first provide support for creating custom procedures and other advanced features and then provide the test harness wrapper.
What do you think?

I have to say that maybe I am missing something, I didn't know about the test harness until today and all the googling I did was not very helpful.

**Comment by tjarvstrand** [comment]
> From what I can see that is a Java library, so it should just work with any Scala version, it doesn't know anything about Scala. Not sure if I am missing something.

I'm not really familiar with the internal but the harness runs an embedded Neo4j which must be using some Scala under the hood which you can see from issues such as [this]( https://github.com/neo4j/neo4j/issues/12687) and [this](https://github.com/neo4j/neo4j/issues/8832).

> While I agree it would be cool to have that, for what I understand (I may be wrong) the test harness is more to test custom procedures and things like that, rather than normal queries.

You may be right. I haven't really used Neo4j much in the past. Do you have any other suggestion for automated testing of queries (or Neo4j-based storage backends in general).

> What do you think?

I'm definitely not saying that this should be at the top of your list of priorities. I only found this library a few days ago and I don't even have clear understanding of what works and what doesn't yet :) I just noticed that I couldn't use the neo4j test harness and poked around a bit to see how you do it for neotypes. It looked like what you have is working and I thought that others might be in the same spot as me and could benefit from it.

**Comment by BalmungSan** [comment]
> I'm not really familiar with the internals but the harness runs an embedded Neo4j which must be using some Scala under the hood which you can see from issues such as this and this.

Oh I didn't know the used **Scala** under the hood, that may be big problem because it means we no longer can provide a simple wrapper over that, we would need to reimplement everything from scratch.

> You may be right. I haven't really used Neo4j much in the past. Do you have any other suggestion for automated testing of queries (or Neo4j-based storage backends in general).

You can take a look at what we do in this very same repo, using [**testcontainers-scala**] to run a real **neo4j** database and run real queries against it
