### ISSUE TITLE
neotypes.Async implicit imports cause divergent implicits

### ISSUE THREAD

**Issue by sloshy** [neotypes/neotypes#35]
I have code that uses `cats-effect` with higher-kinded types in most of my functions. Here's an example that should compile fine using the `cats.effect.Async` typeclass:

```scala
import cats.implicits._
import cats.effect._

def flatMapF[F[_]: Async](f: F[Any]): F[Unit] = f.flatMap(_ => Async[F].unit)
```

This code compiles and works fine unless I import the implicits for `neotypes.Async` by importing `neotypes.implicits.all._` or `neotypes.implicits.syntax.all._`. The code fails to compile due to a divergent implicit leading the compiler to not know which `flatMap` method to call.

Currently using the latest snapshot build from master, built locally (`0.9.1-SNAPSHOT`).

**Comment by sloshy** [comment]
A simple workaround for the time being - to me and anyone else who runs into this - is to only import the implicits you need in a specific scope instead of the whole suite of implicits at once everywhere, such as only `ResultMapper`s or string syntax.

**Comment by BalmungSan** [comment]
So the problem is as follows:

When you call `flatMap` over `fa`, since it does not have the `flatMap` method, the compiler will try to find an _implicit conversion_ from it to something that does has such method.
Then it will find both `cats.syntax.FlatMapSyntax.catsSyntaxFlatMapOps` & `neotypes.implicits.syntax.AsyncSyntax.neotypesSyntaxAsync`, and since your `F[_]` has a context bound of `cats.effect.Async[F]` then both are applicable.

Being honest, I do not think there could be other option except for do not importing the **neotypes** _implicit_. Specially because, in this case, they are equivalent.
The implicits refactor _(#33 )_ allowed to import everything you need and exclude this one. Before it, that would be impossible in user code.
I know that could be tedious, but it is the only solution, excluding it from the implicit scope.

The only other _"alternative"_ would be to have some kind of `allButAsync` object, or to move the `AsyncSyntax` trait outside of the `syntax` package. However, that is essentially the same as above, but more ergonomic. 
Also, IMHO, these feel strange, and solve a very specific issue, that maybe it would be better to leave it to the users instead.

For allowing that, we could remove the `private[neotypes]` from all traits, so users could do this:

```scala
package my.app.implicits

import neotypes.implicits.mappers.AllMappers
import neotypes.implicits.syntax.{CypherSyntax, DriverSyntax, StringSyntax}

object neotypes extends AllMappers with CypherSyntax with DriverSyntax with StringSyntax
````

And then they could use `import my.app.implicits.neotypes._` instead.
@sloshy would that work for you?

@dimafeng  if you want, given #34  is still open, I could do that there.
_(being honest, I was also thinking that making them private wasn't really a good idea)_.

**Comment by sloshy** [comment]
So it seems to me that the entirety of `neotypes.Async` is really more of an internal implementation detail to begin with and not something that users benefit from having in their implicit scope. I don't think most users of the library want a `neotypes.Async`-typed object back, especially since it mainly only matters when creating the `Session` to decide what underlying type is "powering" the rest of the library.

Maybe a clean solution to this would be hiding `neotypes.Async` from the public API entirely and instead providing instances of `Session` itself for each supported type that, internally, use `neotypes.Async` without exposing it and causing implicit conflicts.

**Comment by BalmungSan** [comment]
@sloshy  I do not think hiding `neotypes.Async` would be the cleanest solution.
Ideally, as any **typeclass**, anyone should be able to extend it or implement it for the types they want.
But, it is true that one only needs the implicit when creating the session. And that the syntax for `neotypes.Async` is only useful to the library itself. We could make that one private.

@dimafeng I have a draft in my mind, but I think it is too long for #34
Thus, once that one is closed, I will prepare a new PR that should address this as well as hiding some other thing, and making the _implicits_ **traits** public for any one who would want to combine them as I showed above.
What do you think?

**Comment by sloshy** [comment]
Making the syntax private and not part of the standard implicit scope (or any public importable scope) sounds like a good solution to me.

**Comment by dimafeng** [comment]
@sloshy @BalmungSan wow that's amazing exploration and brainstorm!

@BalmungSan I support the approach with making it private. I'm going to complete and merge #34 tomorrow

**Comment by gvolpe** [comment]
Is there any place in user land where `map` and `flatMap` might be used for `neotypes.Async[F]`? If not I think it should be better to hide this from the public API.

**Comment by dimafeng** [comment]
Fixed/implemented in the scope of https://github.com/neotypes/neotypes/pull/39
