### ISSUE TITLE
Discussion: Transaction as a Resource

### ISSUE THREAD

**Issue by BalmungSan** [neotypes/neotypes#42]
Ok so, back on #39 I made `Transaction[F]` a **Resource**. Thus, the `transaction` method on `Session[F]` returns an `R[Transaction[F]]`. That had the negative consequence that we couldn't use `Id` as the **Resource** of `Future`s. But, it seemed like the best thing to do.
However, I have been thinking about it, and I now believe I was wrong!

First, it is true that a **Transaction** should always be `close`d at the end _(that was the main reason for making it a **Resource**)_.
But, the problem is that it has two ways of being closed: `commit`ted & `rollback`ed.

Second, our `close` implementation tries to `commit` the transaction and if that fails, then it tries to `rollback`. At first, that made sense for me...

> I thought about a case like, creating multiple nodes in the same transaction, but if one of the nodes breaks an unique constraint, the commit would fail, and the rollback seemed reasonable.

... However, the Java driver already do this. If a transaction fails to be committed, nothing will happen. And, calling `commit` will return an exception explaining the problem.

Third, If one wants to manually rollback the transaction _(for any reason)_. Then when the resource `close`s and calls `commit`, it will throw an exception! _(because the transaction was already rollbacked and closed)_.

Note: All these apply only to `IO` _& friends_ TM - `Future` does not have this problem, as its **Resource** is not doing nothing.

------

Thus, my question is:

Should we make a **Transaction** just shared state. instead of a **Resource**. That means, returning `F[Transaction[F]]` instead?
Or maybe, should we keep some internal _(mutable)_ state, that changes if the transaction was `rollback`ed, and check that on the close operation?

Do anyone has any other idea or opinion about this?
I am specially interested in hearing about @gvolpe & @dimafeng

**Comment by gvolpe** [comment]
I think returning `F[Transaction[F]]` makes more sense than treating it as a `Resource` because we want to give the user the power to either rollback or commit, regardless of any defect / error. 

Here's what we do in [redis4cats](https://github.com/profunktor/redis4cats/blob/master/modules/effects/src/main/scala/dev/profunktor/redis4cats/transactions.scala#L27), basically providing a `RedisTransaction` value that takes care of the most common scenario of `commit` / `rollback` functionality using `bracketCase`. 

I think we could do both here? Returning `F[Transaction[F]]` to let the user have the responsibility as well as providing a higher level "Transaction" value that handles the common scenario.

**Comment by dimafeng** [comment]
@BalmungSan thanks for the comprehensive description of the issue and the options! Out of two options - `F[Transaction[F]]` vs internal state, I'm inclined toward the first option as it's more explicit and more predictable

**Comment by BalmungSan** [comment]
Ok, so I think I will go ahead with this:

1. Make `F[Transaction[F]]` instead of `R[Transaction[F]]`.
2. Remove the `close` method on it.
3. Make the **Resource** of `Futures` an `Id` again.

Latter, I will think in some way of creating a **Transaction** on a **Resource** that commits as its close action, but only for _IO & Firends TM_.
