### ISSUE TITLE
ZonedDateTime won't deserialize

### ISSUE THREAD

**Issue by nelsonblaha** [neotypes/neotypes#565]
Despite its mention in [this list](https://neotypes.github.io/neotypes/types.html), I can't seem to get anything to deserialize out of neo4j to a `java.time.ZonedDateTime`. 

I have a case class like:

```case class Availability(start: ZonedDateTime, end: ZonedDateTime)```

And nodes like:
```
{
  "identity": 15,
  "labels": [
    "Availability"
  ],
  "properties": {
"start": "2022-10-14T17:00:00-05:00",
"end": "2022-10-14T20:00:00-05:00"
  }
}
```

And I attempt to deserialize like this:
```
    "MATCH (a: Availability)\n RETURN a1".readOnlyQuery[Availability].list(driver)
```

Neotypes hangs similar to when I submit a malformed query, although putting the query in the browser returns the expected nodes.

My readOnlyQuerys work on other case classes made of more common types. I also tried OffsetDateTime.

**Comment by BalmungSan** [comment]
Hi @nelsonblaha as you can see on these tests here: https://github.com/neotypes/neotypes/blob/main/core-test/src/test/scala/neotypes/DriverSpec.scala#L154-L166 _(I hope that for when you see this the pipeline will already be green)_
The driver does support querying date fields as `ZonedDateTime` records.

So, I guess the problem is something else.
For example, are you sure those are dates rather than `Strings` on a date format?
You say that the driver hangs, do you have some stack trace or log or something that may help us debug the problem?

**Comment by nelsonblaha** [comment]
I think I got it. Sorry for the distraction!
