### ISSUE TITLE
warnings on https://neotypes.github.io/neotypes/

### ISSUE THREAD

**Issue by chenharryhua** [neotypes/neotypes#689]
dear developers, I found a warning on the site:
:warning: The library is under heavy development. Production use is at your own risk and is not recommended. :warning:
I used the lib for a couple of years, it is quite stable in my option. I wonder which part of the lib is unstable and should be more careful when bring it to production use?
Cheers

**Comment by BalmungSan** [comment]
Hi @chenharryhua
In general, the point is that the library has not released a `1.0.0` version yet, meaning we are still free to change the API a lot and experiment with different approaches.
In particular, the current biggest change was making `ResultMapper` an explicit value instead of a typeclass, which may require a lot of changes to existing code _(although we made sure to have an easy migration route)_. This was released on the first milestone for `1.0.0`.

This weekend I hope to release a new milestone that brings **Scala 3** support _(special thanks to @i10416 again 😄)_.
After that, I will see if I do want to make the change to the **Cypher** interpolator proposed on #612 or not.
And depending on that we may have an official `1.0.0` release soon :) _(and remove the warning)_.

Thanks for using the library and I hope it has been useful and that the `1.0.0` won't be too hard :D

**Comment by chenharryhua** [comment]
thank you @BalmungSan . this information is very help. may I close the ticket or let it open in case others may have the same concern?

**Comment by BalmungSan** [comment]
@chenharryhua I will close it once we release `1.0.0` :)

**Comment by BalmungSan** [comment]
https://github.com/neotypes/neotypes/releases/tag/v1.0.0
